#!/usr/bin/env bash
# Install NGINX and Configure Default Homepage
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

sudo service nginx restart
