#!/usr/bin/env bash
# Create an index.html page with a simple "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add a permanent redirect (301)
string="\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $string" /etc/nginx/sites-enabled/default

# Create a custom 404 error page with a French message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "/listen 80 default_server;/a $string" /etc/nginx/sites-enabled/default

# Add a custom HTTP response header with the server's hostname
sudo sed -i "/server_name _/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Restart the Nginx service to apply changes
sudo service nginx restart
