#!/usr/bin/env bash
#My Bash script does the following: The Default server port configuration
#has been restored to ensure proper listening and
#handling of HTTP requests, & optimal server performance & stability
#preventing any potential connectivity issues or service interruptions
#and this script automates that.




sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
