#!/usr/bin/env bash
# script being managed.

case "$1" in
  start)
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;

  stop)
    echo "manage_my_process stopped"
    pid=$(cat /var/run/my_process.pid 2>/dev/null)
    if [ -n "$pid" ]; then
      kill "$pid"
      rm /var/run/my_process.pid
    else
      echo "No running process found."
    fi
    ;;

  restart)
    pid=$(cat /var/run/my_process.pid 2>/dev/null)
    if [ -n "$pid" ]; then
      echo "manage_my_process stopped"
      kill "$pid"
      rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;

  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
