#!/usr/bin/env bash
# 4-to_infinity_and_beyond killed

process_id=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

if [ -n "$process_id" ]; then
    kill "$process_id"
else
    echo "Process not found."
fi
