#!/usr/bin/env bash
# to infinity and beyond process killed

process_ids=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

if [ -n "$process_ids" ]; then
    for pid in $process_ids; do
        kill "$pid"
    done
else
    echo "Process not found."
fi
