#!/usr/bin/env bash
# to infinity and beyond process killed

process_id=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$process_id" ]; then
    kill "$process_id"
else
    echo "Process not found."
fi
