#!/usr/bin/env bash
# parses Apache log files in list format.
# groups all visitors by httP and id
# displays the number of occurrences, IP, and HTTP
# sorted order log code.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
