#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
# Bad luck for the 4th iteration
# Good luck for the 8th iteration
# Best School for all other iterations

count=1

while [ $count -le 20 ]; do
    echo "$count"
    case $count in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((count++))
done
